server:
  port: 8888
spring:
  application:
    name: arco-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/andrerco001/microservices-spring-docker
          default-label: main
          search-paths:
          - 'config-server-repo*'
          - 'config-server-repo/config*'